V1EngineeringInc/MarlinBuilder

- src/configs/common/v1-base-config
This gets the version into M115 and the screen.
> Short build version

- .github/workflows/archim.yml
- .github/workflows/rambo.yml
- .github/workflows/ramps.yml
- .github/workflows/skr1p3.yml
- .github/workflows/skrpro.yml
> Bump to 2.0.6.1

- src/configs/common/v1-base-config
Eeprom reset on flash?? Is that all this does?
> Eeprom reset on flash

- src/configs/boards/mini-rambo
> Just a touch too hot in the middle of summer.

- .github/workflows/archim.yml
- .github/workflows/rambo.yml
- .github/workflows/ramps.yml
- .github/workflows/skr1p3.yml
- .github/workflows/skrpro.yml
> Bump to 2.0.7.2

- .github/workflows/ramps.yml
- src/configs/V1CNC_Ramps
Add a no dual endstop version for the Ramps board.
> Add a no dual endstop version for the Ramps board.

- src/configs/V1CNC_Rambo_Dual
- src/configs/V1CNC_Rambo_DualLR
> Fix the disable for rambo drivers.

- src/configs/V13DP_MiniRambo
- src/configs/V13DP_Ramps_MK8
- src/configs/V1CNC_Archim1
- src/configs/V1CNC_Archim1_Dual
- src/configs/V1CNC_Archim2
- src/configs/V1CNC_Archim2_Dual
- src/configs/V1CNC_MiniRambo
- src/configs/V1CNC_Rambo
- src/configs/V1CNC_Ramps
- src/configs/V1CNC_Skr1p3_2209
- src/configs/V1CNC_Skr1p3_8825
- src/configs/V1CNC_Skr1p3_DualLR_2209
- src/configs/V1CNC_Skr1p3_DualLR_8825
- src/configs/V1CNC_SkrPro_2209
- src/configs/V1ZXY_MiniRambo
- src/configs/V1ZXY_Ramps
There were several missing this VERSION flag, and some had the wrong D, or non-D. 
I'm waiting for the actions to tell me if we need all of these.
> Polished up a bunch of errors in the V1_VERSION.

- src/configs/common/v1-base-config
Related to forum post:
https://forum.v1engineering.com/t/unknown-command-m42/24978/7?u=jeffeb3
> Added DIRECT_PIN_CONTROL, which is needed for M42.

- .github/workflows/rambo.yml
- .github/workflows/ramps.yml
- .github/workflows/skrpro.yml
- src/configs/V13DP_Rambo
- src/configs/V13DP_SkrPro_2209
- src/configs/V1CNC_Ramps_DualLR
- src/configs/V1ZXY_Rambo
- src/configs/V1ZXY_SkrPro_2209
#60 
This fills in the matrix a little. I don't have plans to test these. We really need a way to mark which ones are "Official" vs. "Maybe garbage".
Sorry, I accidentally pushed this straight to main, but I fixed it.
> Added more configurations. These seem logical, but how can you tell?

- src/docs/UBUNTU_BUILD.md
> windows info

- .github/workflows/rambo.yml
- .github/workflows/ramps.yml
> Try to change the library.

- src/configs/common/cnc-config
Defines have been assigned new names.
> Resolve lcd menu errors

- src/configs/boards/skr_pro
New firmware settings for SD card.
> New firmware settings for SD card.

- src/configs/V13RP_SkrPro_2209
> repeat driver current bump

- src/configs/V1CNC_Rambo_DualLR
- src/configs/accessories/dual-drivers-on-yz
- src/configs/accessories/no-dual-endstops
New bugfix uses driver defines to set dual endstops.
> Bugfix changes.

- .github/workflows/archim.yml
- .github/workflows/rambo.yml
- .github/workflows/ramps.yml
- .github/workflows/skr1p3.yml
- .github/workflows/skrpro.yml
- .github/workflows/skrturbo.yml
> Update versions to bugfix-2.1.x and 2.1 for releases.

- src/configs/boards/skr_pro
SKR Pro Wifi Changes for 8266's
> SKR Pro Wifi Changes

- .github/workflows/archim.yml
- .github/workflows/rambo.yml
- .github/workflows/ramps.yml
- .github/workflows/skr1p3.yml
- .github/workflows/skrpro.yml
- .github/workflows/skrturbo.yml
Bring all the workflow assets up to date. Start with skr pro
> Bring all the workflow assets up to date. Start with skr pro

- src/configs/accessories/dual-drivers-on-yz
- src/configs/common/3dp-repeat-config
> Undo LowRider Config
